Add missing unordered_map include to working_files.hh
Building 0.20181225 on FreeBSD fails with:

src/working_files.hh:89:8: error: no template named 'unordered_map' in namespace 'std'
  std::unordered_map<std::string, std::unique_ptr<WorkingFile>> files;
  ~~~~~^
src/working_files.cc:248:8: error: no member named 'unordered_map' in namespace 'std'
  std::unordered_map<uint64_t, int> hash_to_unique;
  ~~~~~^

Signed-off-by: Tobias Kortkamp <tobik@FreeBSD.org>